import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { type Metadata } from "next";
import { Header } from "~/components/shared/Header";
import Providers from "~/providers/Providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={inter.className}>
      <Providers>
        <body className="antialiased">
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
